# Generated by Django 5.1.4 on 2024-12-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_is_service_provider_user_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=50, verbose_name="Phone Number"),
        ),
    ]
